using System;
using System.Collections.Generic;

namespace DataAccessLayer.EntityModel
{
    public partial class CallHistory
    {
        public long CallHistoryMid { get; set; }
        public long? ScriptMid { get; set; }
        public long? DataDid { get; set; }
        public long? LoginMid { get; set; }
        public long? TicketDid { get; set; }
        public byte? RequestSource { get; set; }
        public int? RequestType { get; set; }
        public DateTime? CallStartDateTime { get; set; }
        public DateTime? CallEndDateTime { get; set; }
        public int? OutcomeMid { get; set; }
        public int? SubOutcomeMid { get; set; }
        public string ContactedNumber { get; set; }
        public string Remarks { get; set; }
        public string Para1 { get; set; }
        public string Para2 { get; set; }
        public string Para3 { get; set; }
        public string Para4 { get; set; }
        public string Para5 { get; set; }
        public string Para6 { get; set; }
        public string Para7 { get; set; }
        public string Para8 { get; set; }
        public string Para9 { get; set; }
        public string Para10 { get; set; }
        public string Para11 { get; set; }
        public string Para12 { get; set; }
        public string Para13 { get; set; }
        public string Para14 { get; set; }
        public string Para15 { get; set; }
        public string Para16 { get; set; }
        public string Para17 { get; set; }
        public string Para18 { get; set; }
        public string Para19 { get; set; }
        public string Para20 { get; set; }
        public string Para21 { get; set; }
        public string Para22 { get; set; }
        public string Para23 { get; set; }
        public string Para24 { get; set; }
        public string Para25 { get; set; }
        public string Para26 { get; set; }
        public string Para27 { get; set; }
        public string Para28 { get; set; }
        public string Para29 { get; set; }
        public string Para30 { get; set; }
        public string Para31 { get; set; }
        public string Para32 { get; set; }
        public string Para33 { get; set; }
        public string Para34 { get; set; }
        public string Para35 { get; set; }
        public string Para36 { get; set; }
        public string Para37 { get; set; }
        public string Para38 { get; set; }
        public string Para39 { get; set; }
        public string Para40 { get; set; }
        public string Para41 { get; set; }
        public string Para42 { get; set; }
        public string Para43 { get; set; }
        public string Para44 { get; set; }
        public string Para45 { get; set; }
        public string Para46 { get; set; }
        public string Para47 { get; set; }
        public string Para48 { get; set; }
        public string Para49 { get; set; }
        public string Para50 { get; set; }
        public string Para51 { get; set; }
        public string Para52 { get; set; }
        public string Para53 { get; set; }
        public string Para54 { get; set; }
        public string Para55 { get; set; }
        public string Para56 { get; set; }
        public string Para57 { get; set; }
        public string Para58 { get; set; }
        public string Para59 { get; set; }
        public string Para60 { get; set; }
        public string Para61 { get; set; }
        public string Para62 { get; set; }
        public string Para63 { get; set; }
        public string Para64 { get; set; }
        public string Para65 { get; set; }
        public string Para161 { get; set; }
        public string Para162 { get; set; }
        public string Para163 { get; set; }
        public string Para164 { get; set; }
        public string Para165 { get; set; }
        public string Para166 { get; set; }
        public string Para167 { get; set; }
        public string Para168 { get; set; }
        public string Para169 { get; set; }
        public string Para170 { get; set; }
        public string Para171 { get; set; }
        public string Para172 { get; set; }
        public string Para173 { get; set; }
        public string Para174 { get; set; }
        public string Para175 { get; set; }
        public string Para176 { get; set; }
        public string Para177 { get; set; }
        public string Para178 { get; set; }
        public string Para179 { get; set; }
        public string Para180 { get; set; }
        public string Para181 { get; set; }
        public string Para182 { get; set; }
        public string Para183 { get; set; }
        public string Para184 { get; set; }
        public string Para185 { get; set; }
        public string Para186 { get; set; }
        public string Para187 { get; set; }
        public string Para188 { get; set; }
        public string Para189 { get; set; }
        public string Para190 { get; set; }
        public string Para191 { get; set; }
        public string Para192 { get; set; }
        public string Para193 { get; set; }
        public string Para194 { get; set; }
        public string Para195 { get; set; }
        public string Para196 { get; set; }
        public string Para197 { get; set; }
        public string Para198 { get; set; }
        public string Para199 { get; set; }
        public string Para200 { get; set; }
        public string Para201 { get; set; }
        public string Para202 { get; set; }
        public string Para203 { get; set; }
        public string Para204 { get; set; }
        public string Para205 { get; set; }
        public string Para206 { get; set; }
        public string Para207 { get; set; }
        public string Para208 { get; set; }
        public string Para209 { get; set; }
        public string Para210 { get; set; }
        public string Para211 { get; set; }
        public string Para212 { get; set; }
        public string Para213 { get; set; }
        public string Para214 { get; set; }
        public string Para215 { get; set; }
        public string Para216 { get; set; }
        public string Para217 { get; set; }
        public string Para218 { get; set; }
        public string Para219 { get; set; }
        public string Para220 { get; set; }
        public string Para221 { get; set; }
        public string Para222 { get; set; }
        public string Para223 { get; set; }
        public string Para224 { get; set; }
        public string Para225 { get; set; }
        public string Para226 { get; set; }
        public string Para227 { get; set; }
        public string Para228 { get; set; }
        public string Para229 { get; set; }
        public string Para230 { get; set; }
        public string Para231 { get; set; }
        public string Para232 { get; set; }
        public string Para233 { get; set; }
        public string Para234 { get; set; }
        public string Para235 { get; set; }
        public string Para236 { get; set; }
        public string Para237 { get; set; }
        public string Para238 { get; set; }
        public string Para239 { get; set; }
        public string Para240 { get; set; }
        public string Para241 { get; set; }
        public string Para242 { get; set; }
        public string Para243 { get; set; }
        public string Para244 { get; set; }
        public string Para245 { get; set; }
        public string Para246 { get; set; }
        public string Para247 { get; set; }
        public string Para248 { get; set; }
        public string Para249 { get; set; }
        public string Para250 { get; set; }
        public string Para251 { get; set; }
        public string Para252 { get; set; }
        public string Para253 { get; set; }
        public string Para254 { get; set; }
        public string Para255 { get; set; }
        public string Para256 { get; set; }
        public string Para257 { get; set; }
        public string Para258 { get; set; }
        public string Para259 { get; set; }
        public string Para260 { get; set; }
        public string Para261 { get; set; }
        public string Para262 { get; set; }
        public string Para263 { get; set; }
        public string Para264 { get; set; }
        public string Para265 { get; set; }
        public string Para266 { get; set; }
        public string Para267 { get; set; }
        public string Para268 { get; set; }
        public string Para269 { get; set; }
        public string Para270 { get; set; }
        public string Para271 { get; set; }
        public string Para272 { get; set; }
        public string Para273 { get; set; }
        public string Para274 { get; set; }
        public string Para275 { get; set; }
        public string Para276 { get; set; }
        public string Para277 { get; set; }
        public string Para278 { get; set; }
        public string Para279 { get; set; }
        public string Para280 { get; set; }
        public string Para281 { get; set; }
        public string Para282 { get; set; }
        public string Para283 { get; set; }
        public string Para284 { get; set; }
        public string Para285 { get; set; }
        public string Para286 { get; set; }
        public string Para287 { get; set; }
        public string Para288 { get; set; }
        public string Para289 { get; set; }
        public string Para290 { get; set; }
        public string Para291 { get; set; }
        public string Para292 { get; set; }
        public string Para293 { get; set; }
        public string Para294 { get; set; }
        public string Para295 { get; set; }
        public string Para296 { get; set; }
        public string Para297 { get; set; }
        public string Para298 { get; set; }
        public string Para299 { get; set; }
        public string Para300 { get; set; }
        public byte? FreezeStatus { get; set; }
        public DateTime? CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public string HostName { get; set; }
        public int? ClientMid { get; set; }
        public byte? ReOpenStatus { get; set; }
        public DateTime? ReOpenDateTime { get; set; }
        public long? CallerId { get; set; }
        public byte? ApproveType { get; set; }
        public string PurchaseNo { get; set; }
        public DateTime? CallBackDateTime { get; set; }
        public DateTime? CallStartDateTimeUtc { get; set; }
        public DateTime? CallEndDateTimeUtc { get; set; }
        public DateTime? CreatedDateTimeUtc { get; set; }
        public DateTime? UpdatedDateTimeUtc { get; set; }
    }
}
