using System;
using System.Collections.Generic;

namespace DataAccessLayer.EntityModel
{
    public partial class CollectionDataDetail
    {
        public long CollectionDdid { get; set; }
        public long? DataDid { get; set; }
        public int? ScriptMid { get; set; }
        public long? LoginMid { get; set; }
        public long? DispositionMid { get; set; }
        public string Para301 { get; set; }
        public string Para302 { get; set; }
        public string Para303 { get; set; }
        public string Para304 { get; set; }
        public string Para305 { get; set; }
        public string Para306 { get; set; }
        public string Para307 { get; set; }
        public string Para308 { get; set; }
        public string Para309 { get; set; }
        public string Para310 { get; set; }
        public string Para311 { get; set; }
        public string Para312 { get; set; }
        public string Para313 { get; set; }
        public string Para314 { get; set; }
        public string Para315 { get; set; }
        public string Para316 { get; set; }
        public string Para317 { get; set; }
        public string Para318 { get; set; }
        public string Para319 { get; set; }
        public string Para320 { get; set; }
        public string Para321 { get; set; }
        public string Para322 { get; set; }
        public string Para323 { get; set; }
        public string Para324 { get; set; }
        public string Para325 { get; set; }
        public string Para326 { get; set; }
        public string Para327 { get; set; }
        public string Para328 { get; set; }
        public string Para329 { get; set; }
        public string Para330 { get; set; }
        public string Para331 { get; set; }
        public string Para332 { get; set; }
        public string Para333 { get; set; }
        public string Para334 { get; set; }
        public string Para335 { get; set; }
        public string Para336 { get; set; }
        public string Para337 { get; set; }
        public string Para338 { get; set; }
        public string Para339 { get; set; }
        public string Para340 { get; set; }
        public string Para341 { get; set; }
        public string Para342 { get; set; }
        public string Para343 { get; set; }
        public string Para344 { get; set; }
        public string Para345 { get; set; }
        public string Para346 { get; set; }
        public string Para347 { get; set; }
        public string Para348 { get; set; }
        public string Para349 { get; set; }
        public string Para350 { get; set; }
        public string Para351 { get; set; }
        public string Para352 { get; set; }
        public string Para353 { get; set; }
        public string Para354 { get; set; }
        public string Para355 { get; set; }
        public string Para356 { get; set; }
        public string Para357 { get; set; }
        public string Para358 { get; set; }
        public string Para359 { get; set; }
        public string Para360 { get; set; }
        public string Para361 { get; set; }
        public string Para362 { get; set; }
        public string Para363 { get; set; }
        public string Para364 { get; set; }
        public string Para365 { get; set; }
        public string Para366 { get; set; }
        public string Para367 { get; set; }
        public string Para368 { get; set; }
        public string Para369 { get; set; }
        public string Para370 { get; set; }
        public string Para371 { get; set; }
        public string Para372 { get; set; }
        public string Para373 { get; set; }
        public string Para374 { get; set; }
        public string Para375 { get; set; }
        public string Para376 { get; set; }
        public string Para377 { get; set; }
        public string Para378 { get; set; }
        public string Para379 { get; set; }
        public string Para380 { get; set; }
        public string Para381 { get; set; }
        public string Para382 { get; set; }
        public string Para383 { get; set; }
        public string Para384 { get; set; }
        public string Para385 { get; set; }
        public string Para386 { get; set; }
        public string Para387 { get; set; }
        public string Para388 { get; set; }
        public string Para389 { get; set; }
        public string Para390 { get; set; }
        public string Para391 { get; set; }
        public string Para392 { get; set; }
        public string Para393 { get; set; }
        public string Para394 { get; set; }
        public string Para395 { get; set; }
        public string Para396 { get; set; }
        public string Para397 { get; set; }
        public string Para398 { get; set; }
        public string Para399 { get; set; }
        public string Para400 { get; set; }
        public string Para401 { get; set; }
        public string Para402 { get; set; }
        public string Para403 { get; set; }
        public string Para404 { get; set; }
        public string Para405 { get; set; }
        public string Para406 { get; set; }
        public string Para407 { get; set; }
        public string Para408 { get; set; }
        public string Para409 { get; set; }
        public string Para410 { get; set; }
        public string Para411 { get; set; }
        public string Para412 { get; set; }
        public string Para413 { get; set; }
        public string Para414 { get; set; }
        public string Para415 { get; set; }
        public string Para416 { get; set; }
        public string Para417 { get; set; }
        public string Para418 { get; set; }
        public string Para419 { get; set; }
        public string Para420 { get; set; }
        public string Para421 { get; set; }
        public string Para422 { get; set; }
        public string Para423 { get; set; }
        public string Para424 { get; set; }
        public string Para425 { get; set; }
        public string Para426 { get; set; }
        public string Para427 { get; set; }
        public string Para428 { get; set; }
        public string Para429 { get; set; }
        public string Para430 { get; set; }
        public string Para431 { get; set; }
        public string Para432 { get; set; }
        public string Para433 { get; set; }
        public string Para434 { get; set; }
        public string Para435 { get; set; }
        public string Para436 { get; set; }
        public string Para437 { get; set; }
        public string Para438 { get; set; }
        public string Para439 { get; set; }
        public string Para440 { get; set; }
        public string Para441 { get; set; }
        public string Para442 { get; set; }
        public string Para443 { get; set; }
        public string Para444 { get; set; }
        public string Para445 { get; set; }
        public string Para446 { get; set; }
        public string Para447 { get; set; }
        public string Para448 { get; set; }
        public string Para449 { get; set; }
        public string Para450 { get; set; }
        public string ContactedNumber { get; set; }
        public long? RawDmid { get; set; }
        public byte? FreezeStatus { get; set; }
        public DateTime? CreatedDateTime { get; set; }
        public string CreatedBy { get; set; }
        public DateTime? UpdatedDateTime { get; set; }
        public string UpdatedBy { get; set; }
        public string HostName { get; set; }
    }
}
